modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/Towdium/JustEnoughCalculation/issues"
license="The MIT License (MIT)"

[[mods]]
modId="jecalculation"
version="${version}"
displayName="Just Enough Calculation"
displayURL="https://github.com/Towdium/JustEnoughCalculation"
credits="Thanks to the MCP, Forge and FML guys; along with sesess, Pahimar, MrCrayfish and BedrockMiner for their tutorial."
authors="Towdium, MorningSage, 6LeoY"
description="A simple mod to help you with recipe calculation."
logoFile="icon.png"
[[dependencies.jecalculation]]
modId="architectury"
mandatory=true
versionRange="[8.2.89,)"
ordering="AFTER"
side="BOTH"
[[dependencies.jecalculation]]
modId="jei"
mandatory=false
versionRange="[11.5.0.297,)"
ordering="BEFORE"
side="BOTH"
[[dependencies.jecalculation]]
modId="roughlyenoughitems"
mandatory=false
versionRange="[11.0.633,)"
ordering="BEFORE"
side="BOTH"
