modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Towdium/JustEnoughCalculation/issues"
license="The MIT License (MIT)"

[[mods]]
modId="jecalculation"
version="${file.jarVersion}"
displayName="Just Enough Calculation"
displayURL="https://github.com/Towdium/JustEnoughCalculation"
credits="Thanks to the MCP, Forge and FML guys; along with sesess, Pahimar, MrCrayfish and BedrockMiner for their tutorial."
authors="Towdium, MorningSage"
description="A simple mod to help you with recipe calculation."
[[dependencies.jecalculation]]
    modId="jei"
    mandatory=true
    versionRange="[9.7.0,)"
    ordering="AFTER"
    side="BOTH"
